config/routes.rb
SimpleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user

	default_scope -> { order('created_at DESC')}
	validates :user_id, presence: true
	validates :content, presence: true, length: {maximum: 140}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts, dependent: :destroy


	before_save {self.email = email.downcase}
	before_create :create_remember_token
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

	has_secure_password
	validates :password, length: {minimum: 6}
	
	def feed
    	microposts
  	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private 
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :signed_in_user, only: [:edit, :update]
	before_action :correct_user, only: :destroy

	def create
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			flash[:success] = "Микропост создан"
			redirect_to root_url
		else
			@feed_items = current_user.feed.paginate(page: params[:page])
			render 'static_pages/home'
		end
	end

	def destroy
		@micropost.destroy
		redirect_to root_url
		flash[:success] = "Микропост удален"
	end

	private

		def micropost_params
			params.require(:micropost).permit(:content)
		end

		def correct_user
			@micropost = current_user.microposts.find_by(id: params[:id])
			redirect_to root_url if @micropost.nil?
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Неверный логин или пароль'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		@micropost = current_user.microposts.build
  		@feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]


  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

	def show
		@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
	end

  def new
  	@user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Пользователь удален"
    redirect_to users_url
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
      flash[:success] = "Добро пожаловать!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Профиль успешно обновлен'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Страница"
		if page_title.empty?
			base_title
		else 
			"#{base_title} #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token #создаем новый токен
		cookies.permanent[:remember_token] = remember_token #помещаем зашифрованый токен в куки брайзера
		user.update_attribute(:remember_token, User.encrypt(remember_token)) #сохраняем зашифрованый токен в БД
		self.current_user = user #Устанавливаем текущего пользователя равным данному пользователю
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
    	user == current_user
  	end

  	def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Пожалуйста войдите!"
      end
    end

	def sign_out
		current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = {size: 50})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://vk.com/roman___olegovich">Роман Шпак</a>
		by Roman Olegovich
	</small>
	<nav>
		<ul>
			<li><%= link_to "О нас", about_path %></li>
			<li><%= link_to "Помощь", help_path %></li>
			<li><%= link_to "Контакты", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Sample_app", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Домашняя", root_path%></li>
						<li><%= link_to "О нас", about_path %></li>
						<li><%= link_to "Помощь", help_path %></li>
						<li><%= link_to "Контакты", contact_path %></li>
						<% if signed_in? %>
							<li><%= link_to "Пользователи", users_path %></li>
							<li id="fat-menu" class="dropdown" >
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Аккаунт<b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><%= link_to "Профиль", current_user %></li>
									<li><%= link_to "Настройки", edit_user_path(current_user) %></li>
									<li class="divider"></li>
									<li><%= link_to "Выход", signout_path, method: "delete" %></li>
								</ul>
							</li>
						<% else %>
							<li><%= link_to "Войти", signin_path %></li>
						<% end %>
					</ul>
				</nav>			
			</div>
		</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

</head>
<body>
	<%= render 'layouts/header'%>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"> <%= value%> </div>
		<%end%>
		<%= yield %>
	</div>
	<%= render 'layouts/footer'%>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
	<span class="content"><%= micropost.content %></span>
	<span class="timestamp">
		Опубликовано <%= time_ago_in_words(micropost.created_at) %> назад.
	</span>
	<% if current_user?(micropost.user) %>
		<%= link_to "удалить", micropost, method: :delete, data: {confirm: "Вы уверены?"}, title: micropost.content %>
	<% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any?%>
	<div id="error_explanation">
		<div class="alert alert-error">
			<%= object.errors.count%> <%= Russian.p(object.errors.count, "ошибку", "ошибки", "ошибок")%> содержит форма.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg%> </li></br>
			<%end%>
		</ul>
	</div>
<%end%>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		Опубликовано <%= time_ago_in_words(feed_item.created_at) %> назад.
	</span>
	<% if current_user?(feed_item.user) %>
		<%= link_to "удалить", feed_item, method: :delete, data: {confirm: "Вы уверены?"}, title: feed_item.content %>
	<% end %>
</li>

app/views/shared/_microposts_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Напишите новый пост..." %>
	</div>
	<%= f.submit "Пост", class: "btn btn-large  btn-primary"%>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "Посмотреть мой профиль", current_user %>
</span>
<span>
	<%= current_user.microposts.count %><%= Russian.p(current_user.microposts.count, "Пост.", "Поста.", "Постов.") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'О нас') %>

	<h1>Страница "О нас"</h1>
	<div>Добро пожаловать на страницу "О нас"!</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Контакты') %>

<h1>Страница "Контакты"</h1>
<p>Добро пожаловать на страницу Контактов. Здесь будем отображать данные о разработчиках.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Помощь') %>

	<h1>Страница "Помощь"</h1>
	<p>Щепотка пожертвования в данный проект. Не вздумайте донатить в данный проект. НИКОГДА!</p>

app/views/static_pages/home.html.erb
<%= (provide :title, "Домашняя")%>

<% if signed_in? %>
	<div class="row">
		<aside class="row4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/microposts_form' %>
			</section>
		</aside>
		<div class="span8">
			<h3>Посты</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
	<div class="center hero-unit">
		<h1>Добро пожаловать. Приложение Sample App</h1>
		<%= link_to "Регистрация!", "signup", class: "btn btn-large btn-primary"%> 
	</div>
<% end %>

<%= link_to image_tag("rails.svg", alt: "Rails"), 'http://rubyonrails.org/', class: "img img-circle" %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52%>
	<%= link_to user.name, user%>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "Удалить", user, method: :delete, data: {confirm: "Вы уверены?"} %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Редактирование профиля") %>

<h1>Редактирование профиля</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label "Имя"%>
			<%= f.text_field :name%>

			<%= f.label "Email"%>
			<%= f.text_field :email%>

			<%= f.label "Пароль"%>
			<%= f.password_field :password%>

			<%= f.label "Подтверждение пароля"%>
			<%= f.password_field :password_confirmation%>

			<%= f.submit "Сохранить изменения", class: "btn btn-primary btn-large"%>
		<% end %>

		<%= gravatar_for @user%>
		<a href="http://gravatar.com/emails">Изменить</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Все пользователи') %>
<h1>Все пользователи</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users%>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= (provide :title, "Регистрация")%>
<div class="center hero-unit">
	<h1>Добро пожаловать на страницу "Регистрация"</h1>

</div>


<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>

			<%= render 'shared/error_messages', object: f.object%>

			<%= f.label "Имя" %>
			<%=f.text_field :name %>

			<%= f.label "Email" %>
			<%= f.text_field :email %>

			<%= f.label "Пароль" %>
			<%= f.password_field :password %>

			<%= f.label "Подтверждение пароля" %>
			<%= f.password_field :password_confirmation%>

			<%= f.submit "Создать аккаунт", class: "btn btn-large btn-primary" %>
		<% end %>

	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user, size: 40%>
				<%= @user.name %>
			</h1>
		</section>
		<%= @user.name %>, <%= @user.email %>
	</aside>
	<% if @user.microposts.any? %>
		<div class="micropost_container">
			<h3><%= @user.microposts.count%> <%= Russian.p(@user.microposts.count, "Пост.", "Поста.", "Постов.") %></h3>

			<%= will_paginate @microposts %>
				<ol class="microposts">
					<%= render @microposts %>
				</ol>
			<%= will_paginate @microposts %>

		</div>
	<% end %>
</div>